# Generated by Django 4.1.1 on 2024-01-24 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='id',
        ),
        migrations.AlterField(
            model_name='form',
            name='id_num',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
