# Generated by Django 4.1.1 on 2024-02-08 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0002_remove_form_id_alter_form_id_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id_var', models.AutoField(primary_key=True, serialize=False)),
                ('title_var', models.CharField(max_length=50)),
                ('desc_var', models.CharField(max_length=200)),
            ],
        ),
    ]
